### ISSUE TITLE
morphir-elm make fails with Rule API in sdk package.

### ISSUE THREAD

**Issue by devendrand** [finos/morphir#49]
Exception I got when I tried to create simple rule and rule set 

2021-06-15T09:43:35.385Z] Parsed sources: 4
[2021-06-15T09:43:35.413Z] Inferring types for RuleDemo.upperLimit of size: 13
[2021-06-15T09:43:35.419Z] Generated constraints: 15
[2021-06-15T09:43:35.424Z] Generated solutions: 0
[2021-06-15T09:43:35.425Z] Inferring types for RuleDemo.ruleSet2 of size: 7
[2021-06-15T09:43:35.426Z] Generated constraints: 9
[2021-06-15T09:43:35.455Z] RangeError: Maximum call stack size exceeded
at _Utils_cmp (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:709:17)
at Function.f (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:728:10)
at A2 (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:56:28)
at Function.f (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:14644:15)
at A2 (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:56:28)
at Function.f (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:16700:13)
at A2 (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:56:28)
at Function.f (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:16710:10)
at A2 (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:56:28)
at Function.f (C:\Users\deiveega\AppData\Roaming\npm-global\node_modules\morphir-elm\cli\Morphir.Elm.CLI.js:16714:7)

**Comment by AttilaMihaly** [comment]
Moved to https://github.com/finos/morphir-elm/issues/448

**Comment by devendrand** [comment]
> Moved to [finos/morphir-elm#448](https://github.com/finos/morphir-elm/issues/448)

Thx I was just going to recreate this in morphir-elm.
